services:
  - type: web
    name: task4-user-manager
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Resend__ApiKey
        sync: false
      - key: Resend__FromName
        value: Task4 App
      - key: Resend__FromEmail
        sync: false
